Channel:
  Start: 1
  End: 2  
  Steps: 1

Volume:
  Start: 80    
  End: 90
  Steps: 10

Frequency:
  Start: 34
  End: 36
  Steps: 2

Baselines:
  Baseline_1: 2 # Time in seconds that the EEG measurement starts recording baseline1 | VHP switched OFF â†’ ON
  Baseline_2: 2 # Time in seconds that the EEG measurement starts recording baseline2 | VHP ON, STIM ON, no contact
  Baseline_3: 2 # Time in seconds that the EEG measurement starts recording baseline3 | VHP ON, STIM ON, contact | pre-stimulation baseline before the sweep 

Measurements:
  Number: 2 # Number of measurements for each vol/freq combination
  Duration_on: 1 # Duration in seconds of each measurement ON period
  Duration_off: 1 # Duration in seconds of each measurement OFF period
